field: 09d2a6ba-3fed-4b21-9b93-9ae69ad011d0 # Seiten-Blöcke
fieldLayouts:
  77c5e4bf-fb26-42b2-800e-74368359b41f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 50822843-7888-4ecd-9a73-d860255d5c1b # Mit Hintergrundfarbe anzeigen
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f59ef57-66a7-4cfe-ae1f-542ed75b736a
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: f46dc085-05ca-468b-b359-0a9eb18aac66 # Anker
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7996e430-4e2e-4d52-87a6-701d45a6c019
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: a56c9323-21e9-4911-8f78-c2d74839cce8 # Bild
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e6e09d13-64b5-4092-8811-258dda3876b1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 44830673-872c-4c72-bc4b-bc0b89240fef # CTA-Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8877edaa-e9f0-48e2-a244-f7f91bd84608
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8213518d-e904-48f3-b930-be6aea7baa3c # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d806e6e2-c7ac-4805-8968-22661986c0b2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: bfa04a9a-6be9-4803-9202-a55e93fac144
        userCondition: null
fields:
  8213518d-e904-48f3-b930-be6aea7baa3c: # Button
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: button
    instructions: null
    name: Button
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: false
      autoNoReferrer: false
      customTextMaxLength: 0
      customTextRequired: false
      defaultLinkName: entry
      defaultText: ''
      enableAllLinkTypes: true
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: false
        email:
          allowAliases: false
          disableValidation: false
          enabled: false
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: false
        url:
          allowAliases: false
          disableValidation: false
          enabled: false
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
  44830673-872c-4c72-bc4b-bc0b89240fef: # CTA-Text
    columnSuffix: fnmdtegi
    contentColumnType: text
    fieldGroup: null
    handle: ctaText
    instructions: null
    name: CTA-Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  50822843-7888-4ecd-9a73-d860255d5c1b: # Mit Hintergrundfarbe anzeigen
    columnSuffix: vstztoln
    contentColumnType: string
    fieldGroup: null
    handle: hasBackground
    instructions: 'Der Hintergrund verläuft bis zur Hälfte der Höhe des Blocks. Sie können wählen, ob die obere oder die untere Hälfte farbig hinterlegt wird.'
    name: 'Mit Hintergrundfarbe anzeigen'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Nein
            -
              - value
              - '0'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Obere Hälfte'
            -
              - value
              - top
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Untere Hälfte'
            -
              - value
              - bottom
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  a56c9323-21e9-4911-8f78-c2d74839cce8: # Bild
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: photo
    instructions: null
    name: Bild
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:60ea60f4-d351-4a83-87fb-2db87df0844a' # Medien
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:60ea60f4-d351-4a83-87fb-2db87df0844a' # Medien
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Bild hinzufügen'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  f46dc085-05ca-468b-b359-0a9eb18aac66: # Anker
    columnSuffix: spofslhb
    contentColumnType: text
    fieldGroup: null
    handle: anchor
    instructions: 'Hier können Sie eine Anker-ID angeben, z. B. `schulungen`. Sie können dann in einem anderen Block auf diesen Anker verweisen, z. B. https://becker-gruppe.com/lernen#schulungen'
    name: Anker
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: imageCta
name: 'Bild | CTA'
sortOrder: 14
