field: 09d2a6ba-3fed-4b21-9b93-9ae69ad011d0 # Seiten-Blöcke
fieldLayouts:
  0b2b7434-38fc-41c9-8c38-67711836e9b8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 442dff90-1d33-45d6-9152-ddc6303e40e5 # Stichzeile
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a4a901b9-3c17-4bd6-bda3-decc118bcde0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cad27486-cdd0-4d37-98fd-fad18e7487d8 # Überschrift
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f7a41ea5-8320-4b1a-9f5b-ecc62b491a68
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bcb93ae5-794c-4d5f-9718-504368d1d398 # Anlesetext
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d968a9be-18b6-41f0-a147-eb846ab7b83f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7310f25f-a5f2-4e34-a4b3-ceef5136ac33 # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 71103abf-46cd-4587-9b9b-b3675f779cc8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 018b209c-b610-49b9-ba77-2e27e421463f
        userCondition: null
fields:
  442dff90-1d33-45d6-9152-ddc6303e40e5: # Stichzeile
    columnSuffix: mptlniiz
    contentColumnType: text
    fieldGroup: null
    handle: topline
    instructions: null
    name: Stichzeile
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  7310f25f-a5f2-4e34-a4b3-ceef5136ac33: # Button
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: button
    instructions: null
    name: Button
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: false
      autoNoReferrer: false
      customTextMaxLength: 0
      customTextRequired: false
      defaultLinkName: entry
      defaultText: ''
      enableAllLinkTypes: true
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: false
        email:
          allowAliases: false
          disableValidation: false
          enabled: false
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: false
        url:
          allowAliases: false
          disableValidation: false
          enabled: false
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
  bcb93ae5-794c-4d5f-9718-504368d1d398: # Anlesetext
    columnSuffix: ejpblkhy
    contentColumnType: text
    fieldGroup: null
    handle: teasertext
    instructions: null
    name: Anlesetext
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  cad27486-cdd0-4d37-98fd-fad18e7487d8: # Überschrift
    columnSuffix: yyzhxshg
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Überschrift
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: intro
name: Intro
sortOrder: 1
