field: 09d2a6ba-3fed-4b21-9b93-9ae69ad011d0 # Seiten-Blöcke
fieldLayouts:
  c4873916-2efb-4d39-a758-d70e13688fe6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8e77fee8-35f4-41e3-aad7-a6873d5c982f # Stellenangebote
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 43b726c5-eca2-4c69-8198-70896b415b3c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a97eb305-0655-42a2-9730-9f4326c06a5e # Anker
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4ff0b94f-b873-4d5f-8971-07155b487298
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 7216f276-7a2f-4c3f-a290-7f67de70a6b8
        userCondition: null
fields:
  8e77fee8-35f4-41e3-aad7-a6873d5c982f: # Stellenangebote
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: jobs
    instructions: 'Wählen Sie, welche Stellenangebote Sie anzeigen möchten. Wenn das Feld leer gelassen wird, werden alle veröffentlichten Stellenangebote angezeigt.'
    name: Stellenangebote
    searchable: false
    settings:
      allowSelfRelations: false
      localizeRelations: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: 'Stellenangebot(e) hinzufügen'
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  a97eb305-0655-42a2-9730-9f4326c06a5e: # Anker
    columnSuffix: bckdzkmm
    contentColumnType: text
    fieldGroup: null
    handle: anker
    instructions: 'Hier können Sie eine Anker-ID angeben, z. B. `stellenangebote`. Sie können dann in einem anderen Block auf diesen Anker verweisen, z. B. https://becker-gruppe.com/karriere#stellenangebote'
    name: Anker
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: jobslist
name: Job(s)
sortOrder: 11
