field: 97ace654-b6cb-4127-836e-4b22fc09eea4 # Listenelemente
fieldLayouts:
  52aad673-6c0a-43eb-8135-51561bb32b5b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5be4e053-248e-458a-9d62-e43b55b30de0 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7520f7ed-c317-4078-8f92-bbbc97409bb8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: eba223f5-fcf7-4b6e-b704-0d893028ce4d
        userCondition: null
fields:
  5be4e053-248e-458a-9d62-e43b55b30de0: # Text
    columnSuffix: sexscwya
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: listelement
name: Listenpunkt
sortOrder: 1
