field: 09d2a6ba-3fed-4b21-9b93-9ae69ad011d0 # Seiten-Blöcke
fieldLayouts:
  0e44ab94-6a86-4955-af02-3f90891729b5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0349d1e7-5b89-4b96-821c-93469b179029 # Topline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 75cb455e-cd83-40d8-8085-a59b20def7b5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5614bd2c-f68c-4445-9675-6bd963bbc831 # Überschrift
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4273bb82-aaf3-468c-8d16-133b6dadab9c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cf5de057-3198-4bd7-b414-acc9bb572d56 # Fotos
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 04a0f487-a8b5-4300-add2-785e298d8309
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0dd849df-12fe-42cb-aba8-96f66073b98f
        userCondition: null
fields:
  0349d1e7-5b89-4b96-821c-93469b179029: # Topline
    columnSuffix: otvlmhtv
    contentColumnType: text
    fieldGroup: null
    handle: topline
    instructions: null
    name: Topline
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  5614bd2c-f68c-4445-9675-6bd963bbc831: # Überschrift
    columnSuffix: mxcvjkyx
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Überschrift
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  cf5de057-3198-4bd7-b414-acc9bb572d56: # Fotos
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: photos
    instructions: null
    name: Fotos
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:60ea60f4-d351-4a83-87fb-2db87df0844a' # Medien
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 2
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:60ea60f4-d351-4a83-87fb-2db87df0844a' # Medien
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Foto(s) hinzufügen'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: newsletter
name: Newsletter
sortOrder: 19
