field: 09d2a6ba-3fed-4b21-9b93-9ae69ad011d0 # Seiten-Blöcke
fieldLayouts:
  0dc93099-4b49-4cb8-8975-22cf29c3dc5c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d454a9d9-799e-46b4-859c-d924f8b78829 # Mit Hintergrund anzeigen
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2248ee6d-715a-4715-b62f-34e597a72c51
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a22b472b-9fea-4aa5-96fd-0bfbbf80f210 # Hintergrund-Farbe
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c11a953-e3f2-4d44-abba-825fcaf9e14a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 07d53270-3e59-459c-ac47-05be5f5c9362 # Fotos
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff3396c4-6d58-42ff-a1e7-e9d7ddd379e4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5c85e888-d84e-40ed-b38a-795747ea8dc1 # Stichzeile
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bf90faf6-e93d-4be3-acca-9598378b62ca
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1717e6e3-574a-44ad-a9fe-49a509454425 # Überschrift
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6af59b3f-8ac7-46ab-9d48-036a97f5ff33
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 20dfeeb7-484b-4538-9f0c-00fa26a8672c # Anlesetext
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5bc116fa-9697-4a79-bd45-5ddf94faf7ad
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2f37751b-934d-44ae-8877-5585b3f82cc3 # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3eb1b4e7-4560-4ca7-945f-b8c09d929d6b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d59934a3-f790-45d9-b170-9008709863d1
        userCondition: null
fields:
  2f37751b-934d-44ae-8877-5585b3f82cc3: # Button
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: button
    instructions: null
    name: Button
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: false
      autoNoReferrer: false
      customTextMaxLength: 0
      customTextRequired: false
      defaultLinkName: entry
      defaultText: ''
      enableAllLinkTypes: true
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: false
        email:
          allowAliases: false
          disableValidation: false
          enabled: false
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: false
        url:
          allowAliases: false
          disableValidation: false
          enabled: false
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
  5c85e888-d84e-40ed-b38a-795747ea8dc1: # Stichzeile
    columnSuffix: nttsxqtv
    contentColumnType: text
    fieldGroup: null
    handle: topline
    instructions: null
    name: Stichzeile
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  07d53270-3e59-459c-ac47-05be5f5c9362: # Fotos
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: photos
    instructions: null
    name: Fotos
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:60ea60f4-d351-4a83-87fb-2db87df0844a' # Medien
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 2
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:60ea60f4-d351-4a83-87fb-2db87df0844a' # Medien
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Fotos hinzufügen'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  20dfeeb7-484b-4538-9f0c-00fa26a8672c: # Anlesetext
    columnSuffix: oplgjxbd
    contentColumnType: text
    fieldGroup: null
    handle: teasertext
    instructions: null
    name: Anlesetext
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  1717e6e3-574a-44ad-a9fe-49a509454425: # Überschrift
    columnSuffix: zccumlbs
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Überschrift
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a22b472b-9fea-4aa5-96fd-0bfbbf80f210: # Hintergrund-Farbe
    columnSuffix: tvkukshc
    contentColumnType: string
    fieldGroup: null
    handle: backgroundColor
    instructions: null
    name: Hintergrund-Farbe
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Hell
            -
              - value
              - light
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Dunkel
            -
              - value
              - dark
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  d454a9d9-799e-46b4-859c-d924f8b78829: # Mit Hintergrund anzeigen
    columnSuffix: vyvtynxv
    contentColumnType: string
    fieldGroup: null
    handle: hasBackground
    instructions: null
    name: 'Mit Hintergrund anzeigen'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Nein
            -
              - value
              - '0'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Obere Häfte'
            -
              - value
              - top
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Untere Hälfte'
            -
              - value
              - bottom
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: photointro
name: Foto-Intro
sortOrder: 2
