field: 09d2a6ba-3fed-4b21-9b93-9ae69ad011d0 # Seiten-Blöcke
fieldLayouts:
  0a8ba19e-f2da-434a-963b-2a54554c63be:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3551f7ba-4618-408d-8559-aa3526923e09 # Mit Hintergrundfarbe anzeigen
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 37afcbd7-de38-4f77-900b-1d61187d442f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 848dbd3c-cccc-4a06-b694-784a31dd3782 # Spaltenzahl
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 09d5b310-ebd6-4991-be4c-44648ef37c8d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 0e7e765f-1fdb-47b8-9539-218ab9fb080f # Anker
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cee7da13-afa1-4013-ac7a-eb148b33043c
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 535f856a-d39d-41d3-a444-1acb7c51689a # Listenelemente
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dcfbde51-09e5-45aa-a3b5-f5711a05b917
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 991f0484-6036-44f0-b56a-e22af22c0285
        userCondition: null
fields:
  0e7e765f-1fdb-47b8-9539-218ab9fb080f: # Anker
    columnSuffix: qalnjtrw
    contentColumnType: text
    fieldGroup: null
    handle: anchor
    instructions: 'Hier können Sie eine Anker-ID angeben, z. B. `schulungen`. Sie können dann in einem anderen Block auf diesen Anker verweisen, z. B. https://becker-gruppe.com/lernen#schulungen'
    name: Anker
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  535f856a-d39d-41d3-a444-1acb7c51689a: # Listenelemente
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: listitems
    instructions: null
    name: Listenelemente
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 523276551
      columns:
        __assoc__:
          -
            - bae4f2fe-7754-4d47-8062-a4b19d5c5868 # Überschrift
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 5a503633-46e9-4387-bf97-dfdf0b1c429d # Text
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - b18a48a6-252c-449a-ac3b-42840a8703b8 # Icon
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_9_listitems}}'
      fieldLayout: matrix
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: 'Listenelement hinzufügen'
      staticField: null
    translationKeyFormat: null
    translationMethod: none
    type: verbb\supertable\fields\SuperTableField
  848dbd3c-cccc-4a06-b694-784a31dd3782: # Spaltenzahl
    columnSuffix: qkqexqtz
    contentColumnType: string
    fieldGroup: null
    handle: columnCount
    instructions: null
    name: Spaltenzahl
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - '3'
            -
              - value
              - '3'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '2'
            -
              - value
              - '2'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  3551f7ba-4618-408d-8559-aa3526923e09: # Mit Hintergrundfarbe anzeigen
    columnSuffix: xnrcqkqw
    contentColumnType: boolean
    fieldGroup: null
    handle: hasBackground
    instructions: null
    name: 'Mit Hintergrundfarbe anzeigen'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: simpleList
name: 'Einfache Liste'
sortOrder: 8
