field: 09d2a6ba-3fed-4b21-9b93-9ae69ad011d0 # Seiten-Blöcke
fieldLayouts:
  8e3b7bf1-2132-4465-be20-f4fa4ce462c8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ee39c1ba-ce65-427c-ae58-308e7d56517e # Überschrift
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c3ef932b-20ee-4929-b533-89f057d5ed54
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 992877db-1e14-4433-b015-356aaf998fdf # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: db92022d-e3a5-4fd4-af99-ad825b0efb14
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3a83a1da-8d5e-4c6d-8cbd-b1a68cdc92c5 # Teammitglied(er)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5dd7c3e4-f417-4701-ab8e-f6100e8ab5a8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1ae56178-8974-470c-aa80-00472b4afba6 # Mit Hintergrundfarbe anzeigen
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9dfef97b-ff5f-413a-b940-b152601a2fbb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: edf72581-4283-4eec-b71f-f8fa75f72686
        userCondition: null
fields:
  1ae56178-8974-470c-aa80-00472b4afba6: # Mit Hintergrundfarbe anzeigen
    columnSuffix: grwdjqdz
    contentColumnType: boolean
    fieldGroup: null
    handle: hasBackground
    instructions: null
    name: 'Mit Hintergrundfarbe anzeigen'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  3a83a1da-8d5e-4c6d-8cbd-b1a68cdc92c5: # Teammitglied(er)
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: members
    instructions: 'Falls in diesem Feld keine Person(en) hinzugefügt wird, wird das gesamte Team nach Geschäftsbereich sortiert ausgegeben.'
    name: Teammitglied(er)
    searchable: false
    settings:
      allowSelfRelations: false
      localizeRelations: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: 'Person(en) hinzufügen'
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  992877db-1e14-4433-b015-356aaf998fdf: # Text
    columnSuffix: ryqewdav
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ee39c1ba-ce65-427c-ae58-308e7d56517e: # Überschrift
    columnSuffix: rawtvkxc
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Überschrift
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: teammembers
name: Teammitglied(er)
sortOrder: 16
