field: 09d2a6ba-3fed-4b21-9b93-9ae69ad011d0 # Seiten-Blöcke
fieldLayouts:
  669e1b4c-4edc-41d2-adae-3a4964b67837:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: faf1c7fa-f3cd-48b2-afc4-7ae93eebbf5b # Mit Hintergrund anzeigen
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0573bba4-e658-47b0-8b10-a9e6de8f92a8
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 7ba8a046-bbe1-40ca-bd81-0193ffc9d49d # Anker
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3f743736-5876-4bda-a934-1ee26ae1ddd3
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 41b6fcb3-7903-4934-bfd1-821b407bdb63 # Textblock
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 760e895c-87a4-40a7-be4a-dff39d3ecac8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 30f38a75-75e6-4097-8cf7-42f8ae0e055b # Liste
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f91b572-d382-4a18-9e9f-181699a20a35
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 60cbcf40-87ce-4ee9-ba47-eba54b5321c5
        userCondition: null
fields:
  7ba8a046-bbe1-40ca-bd81-0193ffc9d49d: # Anker
    columnSuffix: ccjmhfhm
    contentColumnType: text
    fieldGroup: null
    handle: anchor
    instructions: 'Hier können Sie eine Anker-ID angeben, z. B. `schulungen`. Sie können dann in einem anderen Block auf diesen Anker verweisen, z. B. https://becker-gruppe.com/lernen#schulungen'
    name: Anker
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  30f38a75-75e6-4097-8cf7-42f8ae0e055b: # Liste
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: list
    instructions: null
    name: Liste
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 397842108
      columns:
        __assoc__:
          -
            - 272f94de-e93a-4b42-b15b-dc80980aeab2 # Listen-Icon
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 9343d92c-fadb-4442-8f32-f6693dd2d970 # Listen-Überschrift
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 97ace654-b6cb-4127-836e-4b22fc09eea4 # Listenelemente
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_8_list}}'
      fieldLayout: row
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: null
      staticField: true
    translationKeyFormat: null
    translationMethod: none
    type: verbb\supertable\fields\SuperTableField
  41b6fcb3-7903-4934-bfd1-821b407bdb63: # Textblock
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: textblock
    instructions: null
    name: Textblock
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 639733784
      columns:
        __assoc__:
          -
            - 5bf7d99b-6cb1-4dcc-be01-2e4118a9b01f # Überschrift
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 0e57a49f-c929-4a37-89d2-da868ffdcb94 # Text
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_8_textblock}}'
      fieldLayout: row
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: null
      staticField: true
    translationKeyFormat: null
    translationMethod: none
    type: verbb\supertable\fields\SuperTableField
  faf1c7fa-f3cd-48b2-afc4-7ae93eebbf5b: # Mit Hintergrund anzeigen
    columnSuffix: ufibthub
    contentColumnType: boolean
    fieldGroup: null
    handle: hasBackground
    instructions: null
    name: 'Mit Hintergrund anzeigen'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: textList
name: 'Text | Liste'
sortOrder: 7
