columnSuffix: null
contentColumnType: string
fieldGroup: bb8805d1-ef12-494d-bbc1-8d3668cf097f # Common
handle: pageBlocks
instructions: null
name: Seiten-Blöcke
searchable: false
settings:
  contentTable: '{{%matrixcontent_pageblocks}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
