changedFieldIndicator: 706881538
field: 4ddc5c9a-3ca5-4302-8e23-1d2f86d1ffb7 # Links
fieldLayouts:
  a585abf5-20c5-41dc-8264-9877ef46a115:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: bbb97d7e-1dd2-4d3b-bfe3-772707e11cea # Link
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eef3a562-9bdb-4465-bb86-f8e18bd15fb3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 30c358ff-d041-4f46-9dd8-a2837a0016da # Grafik
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 07b3933b-35fc-46ea-8bb1-4d200fb6bc46
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b069aa75-8c64-4fd3-bcad-e4c5d906997d # Anlesetext
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 11506dad-5ece-4010-880b-12ae7212ab6e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 54a73e76-43bd-4881-b026-b0d0ce36bbc3
        userCondition: null
fields:
  30c358ff-d041-4f46-9dd8-a2837a0016da: # Grafik
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Grafik
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:60ea60f4-d351-4a83-87fb-2db87df0844a' # Medien
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:60ea60f4-d351-4a83-87fb-2db87df0844a' # Medien
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Grafik hinzufügen'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  b069aa75-8c64-4fd3-bcad-e4c5d906997d: # Anlesetext
    columnSuffix: gxaomprk
    contentColumnType: text
    fieldGroup: null
    handle: teasertext
    instructions: null
    name: Anlesetext
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  bbb97d7e-1dd2-4d3b-bfe3-772707e11cea: # Link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: linking
    instructions: null
    name: Link
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: false
      autoNoReferrer: false
      customTextMaxLength: 0
      customTextRequired: false
      defaultLinkName: entry
      defaultText: ''
      enableAllLinkTypes: true
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: false
        email:
          allowAliases: false
          disableValidation: false
          enabled: false
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: false
        url:
          allowAliases: false
          disableValidation: false
          enabled: false
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
