changedFieldIndicator: 1737973689
field: 535f856a-d39d-41d3-a444-1acb7c51689a # Listenelemente
fieldLayouts:
  e92aa246-b54e-48fa-a801-deb3b41669ba:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: bae4f2fe-7754-4d47-8062-a4b19d5c5868 # Überschrift
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 38a9dee8-7578-4324-b0c3-6951c9c2c38d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5a503633-46e9-4387-bf97-dfdf0b1c429d # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6b508aab-476e-4d9b-878c-f0e806244700
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b18a48a6-252c-449a-ac3b-42840a8703b8 # Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9b5e8b6f-9b51-4342-80ec-864948ed932f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 62309388-7a4c-45d2-a0f1-06b2607c3958
        userCondition: null
fields:
  5a503633-46e9-4387-bf97-dfdf0b1c429d: # Text
    columnSuffix: bcamfvgj
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Simple.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  b18a48a6-252c-449a-ac3b-42840a8703b8: # Icon
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: icon
    instructions: null
    name: Icon
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:60ea60f4-d351-4a83-87fb-2db87df0844a' # Medien
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:60ea60f4-d351-4a83-87fb-2db87df0844a' # Medien
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Icon hinzufügen'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  bae4f2fe-7754-4d47-8062-a4b19d5c5868: # Überschrift
    columnSuffix: odzipnci
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Überschrift
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
