changedFieldIndicator: 784556771
field: f131501e-a413-4ae0-add2-8aa059cea708 # Liste
fieldLayouts:
  4888b0e9-9a57-48e9-bd1a-f5eea3ed9ea2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 62774804-4122-42b1-99b4-80391e51a517 # Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aebc834c-bc39-4cb8-a1f7-64aca7c9d780
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0b6a3d27-cf25-4c7b-9c1a-b36fdae1b496 # Überschrift
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d948bae3-cfec-4730-807b-3d9f43995bab
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dc887b28-3f0a-4274-b1d8-95fe6a7c47e1 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3b4a81a4-b349-47de-b444-47015d1ee450
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ef2c692e-ef9d-4ca5-b021-60252339d7f9
        userCondition: null
fields:
  0b6a3d27-cf25-4c7b-9c1a-b36fdae1b496: # Überschrift
    columnSuffix: pszilmul
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Überschrift
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  62774804-4122-42b1-99b4-80391e51a517: # Icon
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: icon
    instructions: null
    name: Icon
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:60ea60f4-d351-4a83-87fb-2db87df0844a' # Medien
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:60ea60f4-d351-4a83-87fb-2db87df0844a' # Medien
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Icon hinzufügen'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  dc887b28-3f0a-4274-b1d8-95fe6a7c47e1: # Text
    columnSuffix: zlaeandw
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Simple.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
