changedFieldIndicator: 505141874
field: f9571062-6a9d-4ecd-9db8-16f35541bc57 # Abstand
fieldLayouts:
  1d288440-7932-405a-b7a6-55adad5b6982:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: aa743709-4f8c-4453-ad66-178da072a044 # Oben
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c76c24d7-98f9-41f9-a3f5-f34f275ecca0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8513723e-6250-488c-8e2a-b1541b2ad57a # Unten
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b8f43943-9552-4a66-80d1-f83d5290005e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 303bdff7-71d6-4a86-a3e5-1f2a874d57fd
        userCondition: null
fields:
  8513723e-6250-488c-8e2a-b1541b2ad57a: # Unten
    columnSuffix: pawsaxmd
    contentColumnType: string
    fieldGroup: null
    handle: bottom
    instructions: null
    name: Unten
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Normal
            -
              - value
              - normal
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Kein Abstand'
            -
              - value
              - '0'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  aa743709-4f8c-4453-ad66-178da072a044: # Oben
    columnSuffix: kvmgjdbz
    contentColumnType: string
    fieldGroup: null
    handle: top
    instructions: null
    name: Oben
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Normal
            -
              - value
              - normal
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Kein Abstand'
            -
              - value
              - '0'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
