defaultPlacement: end
enableVersioning: true
handle: startseite
name: Startseite
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primäre eintrag Seite'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  6ddfbcee-cb13-4044-85d4-2e3f68a773bf: # Craft Boilerplate
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
